CREATE TABLE `TB_BITACORA` (
	`ID`	INTEGER  PRIMARY KEY AUTOINCREMENT,
	`PAQUETE`	INTEGER,
	`TRAMA`	INTEGER NOT NULL,
	`TEXTO`	TEXT,
	`INTENTO`	INTEGER NOT NULL,
	`ESTADO`	INTEGER NOT NULL,
	`FECHA_ACTUALIZADO`	TEXT NOT NULL
);



CREATE TABLE TB_PAQUETE(
	ID	INTEGER PRIMARY KEY AUTOINCREMENT,
	FECHA_CARGADO	TEXT,
	FECHA_ACTUALIZADO	TEXT,
	ESTADO	INTEGER
);



//Central

CREATE TABLE TB_BITACORA (
	ID	INTEGER  PRIMARY KEY AUTOINCREMENT,
	PAQUETE	INTEGER,
	TRAMA	INTEGER NOT NULL,
	TEXTO	TEXT,
	INTENTO	INTEGER NOT NULL,
	IP_ORIGEN TEXT NOT NULL,
	ESTACION TEXT NOT NULL,
	ESTADO	INTEGER NOT NULL,
	FECHA_CREADO TEXT NOT NULL,
	FECHA_ACTUALIZADO	TEXT NOT NULL
);
